local mod = get_mod("Let Me See My Scanner")

return {
    name = mod:localize("mod_name"),
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "general_settings_group",
                type = "group",
                title = "general_settings",
                tab = mod:localize("tab_general"),
                sub_widgets = {
                    {
                        setting_id = "transparency_amount",
                        type = "numeric",
                        range = { 0, 1 },
                        default_value = 0,
                        decimals_number = 2,
                        step_size_value = 0.05,
                        title = "transparency_amount",
                        tooltip = "transparency_amount_description",
                    },
                    {
                        setting_id = "smooth_fade",
                        type = "checkbox",
                        default_value = true,
                        title = "smooth_fade",
                        tooltip = "smooth_fade_description",
                    },
                    {
                        setting_id = "fade_duration",
                        type = "numeric",
                        range = { 0.05, 2 },
                        default_value = 0.3,
                        decimals_number = 2,
                        step_size_value = 0.05,
                        title = "fade_duration",
                        tooltip = "fade_duration_description",
                    },
                    {
                        setting_id = "caption_opacity",
                        type = "numeric",
                        range = { 0, 1 },
                        default_value = 0,
                        decimals_number = 2,
                        step_size_value = 0.01,
                        title = "caption_opacity",
                        tooltip = "caption_opacity_description",
                    },
                },
            },
            {
                setting_id = "toggle_visibility_header",
                type = "group",
                title = "toggle_visibility_header",
                tab = mod:localize("tab_visibility"),
                sub_widgets = {
                    {
                        setting_id = "hide_hudelementcrosshair",
                        type = "checkbox",
                        default_value = true,
                        title = "hide_crosshair",
                        tooltip = "hide_crosshair_description",
                    },
                    {
                        setting_id = "hide_hudelementcrosshairhud",
                        type = "checkbox",
                        default_value = true,
                        title = "hide_crosshair_hud",
                        tooltip = "hide_crosshair_hud_description",
                    },
                    {
                        setting_id = "hide_hudelementdodgecounter",
                        type = "checkbox",
                        default_value = true,
                        title = "hide_dodge_counter",
                        tooltip = "hide_dodge_counter_description",
                    },
                    {
                        setting_id = "hide_hudelementdodgecount",
                        type = "checkbox",
                        default_value = true,
                        title = "hide_dodge_count",
                        tooltip = "hide_dodge_count_description",
                    },
                    {
                        setting_id = "hide_hudelementstamina",
                        type = "checkbox",
                        default_value = true,
                        title = "hide_stamina",
                        tooltip = "hide_stamina_description",
                    },
                    {
                        setting_id = "hide_ability_icons",
                        type = "checkbox",
                        default_value = true,
                        title = "hide_ability_icons",
                        tooltip = "hide_ability_icons_description",
                    },
                    {
                        setting_id = "hide_buff_bars",
                        type = "checkbox",
                        default_value = true,
                        title = "hide_buff_bars",
                        tooltip = "hide_buff_bars_description",
                    },
                },
            },
        },
    },
}
